version: '3.1'

services:
  app:
    build: polar_app
    ports:
      - "5002:5002"
    stdin_open: true
    tty: true
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_USER: polar_user
      MYSQL_PASSWORD: 2004
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: 3306

